services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:80"              
    environment:
      DB_HOST: ${DB_HOST}             
      DB_PORT: ${DB_PORT_APP}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src:/var/www/html          
    depends_on:
      - db                           

  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MARIADB_DATABASE: ${DB_DATABASE}          
      MARIADB_USER: ${DB_USERNAME}              
      MARIADB_PASSWORD: ${DB_PASSWORD}          
  
    ports:
      - "${DB_PORT_HOST}:3306"       
    volumes:
      - db_data:/var/lib/mysql        

volumes:
  db_data:                            